{% set name = "flatten-dict" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 506a96b6e6f805b81ae46a0f9f31290beb5fa79ded9d80dbe1b7fa236ab43076

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - pathlib2 >=2.3,<3.0
    - python >={{ python_min }}
    - setuptools
    - six >=1.12,<2.0

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - flatten_dict
    - flatten_dict.tests
  commands:
    - pip check

about:
  home: https://github.com/ianlini/flatten-dict
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A flexible utility for flattening and unflattening dict-like objects in Python.

extra:
  recipe-maintainers:
    - bgruening
    - efiop
